services:
  chopsticks:
    image: node:20
    command:
      - "npx"
      - "@acala-network/chopsticks@latest"
      - "xcm"
      - "--r=/root/data/polkadot.yml"
      - "--p=/root/data/polkadot-coretime.yml"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./chopsticks-vol:/root/data:ro
      - ./artefacts:/root/artefacts:ro

  check:
    image: node:20
    command:
      - "node"
      - "/root/coretime-migration-check/main.js"
      - "/root/artefacts/polkadot_runtime.compact.compressed.wasm"
    volumes:
      - ./coretime-migration-check:/root/coretime-migration-check:ro
      - ./artefacts:/root/artefacts:ro
    environment:
      - RELAY_CHAIN_RPC=ws://chopsticks:8001
      - CORETIME_CHAIN_RPC=ws://chopsticks:8000
